//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestreino
{
    using System;
    using System.Collections.Generic;
    
    public partial class GT_RespAptidaoCardio
    {
        public int ID { get; set; }
        public int GT_SOCIOS_ID { get; set; }
        public int GT_TipoTesteCardio_ID { get; set; }
        public Nullable<int> CARGA { get; set; }
        public Nullable<int> TEMPO { get; set; }
        public Nullable<int> FC4M { get; set; }
        public Nullable<int> FC5M { get; set; }
        public Nullable<int> FC400M { get; set; }
        public Nullable<int> FC3M { get; set; }
        public Nullable<int> FC15M { get; set; }
        public Nullable<int> FCFIMTESTE { get; set; }
        public Nullable<int> VELOCIDADE { get; set; }
        public Nullable<int> VELOCIDADEMPH { get; set; }
        public Nullable<int> DISTANCIA { get; set; }
        public Nullable<int> V02CARGA { get; set; }
        public Nullable<int> MEDIA { get; set; }
        public Nullable<int> VO2MAX { get; set; }
        public Nullable<int> CUSTO { get; set; }
        public Nullable<int> CUSTOCAL { get; set; }
        public Nullable<int> VO2DESEJAVEL { get; set; }
        public Nullable<int> CLASSIFICACAO { get; set; }
        public Nullable<int> RESP_SUMMARY { get; set; }
        public string RESP_DESCRICAO { get; set; }
        public Nullable<int> PERCENTIL { get; set; }
        public int INSERIDO_POR { get; set; }
        public Nullable<int> ACTUALIZADO_POR { get; set; }
        public Nullable<int> REMOVIDO_POR { get; set; }
        public System.DateTime DATA_INSERCAO { get; set; }
        public Nullable<System.DateTime> DATA_ACTUALIZACAO { get; set; }
        public Nullable<System.DateTime> DATA_REMOCAO { get; set; }
    
        public virtual GT_SOCIOS GT_SOCIOS { get; set; }
        public virtual GT_TipoTesteCardio GT_TipoTesteCardio { get; set; }
    }
}
