//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestreino
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GESTREINO_Entities : DbContext
    {
        public GESTREINO_Entities()
            : base("name=GESTREINO_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GRL_ANO_LECTIVO> GRL_ANO_LECTIVO { get; set; }
        public virtual DbSet<GRL_ARQUIVOS> GRL_ARQUIVOS { get; set; }
        public virtual DbSet<GRL_ARQUIVOS_TIPO_DOCS> GRL_ARQUIVOS_TIPO_DOCS { get; set; }
        public virtual DbSet<GRL_DEFINICOES> GRL_DEFINICOES { get; set; }
        public virtual DbSet<GRL_ENDERECO_CIDADE> GRL_ENDERECO_CIDADE { get; set; }
        public virtual DbSet<GRL_ENDERECO_MUN_DISTR> GRL_ENDERECO_MUN_DISTR { get; set; }
        public virtual DbSet<GRL_ENDERECO_PAIS> GRL_ENDERECO_PAIS { get; set; }
        public virtual DbSet<GRL_TOKENS> GRL_TOKENS { get; set; }
        public virtual DbSet<GRL_TOKENS_TIPOS> GRL_TOKENS_TIPOS { get; set; }
        public virtual DbSet<INST_APLICACAO> INST_APLICACAO { get; set; }
        public virtual DbSet<INST_APLICACAO_ARQUIVOS> INST_APLICACAO_ARQUIVOS { get; set; }
        public virtual DbSet<INST_APLICACAO_CONTACTOS> INST_APLICACAO_CONTACTOS { get; set; }
        public virtual DbSet<INST_APLICACAO_ENDERECOS> INST_APLICACAO_ENDERECOS { get; set; }
        public virtual DbSet<PES_ARQUIVOS> PES_ARQUIVOS { get; set; }
        public virtual DbSet<PES_CONTACTOS> PES_CONTACTOS { get; set; }
        public virtual DbSet<PES_ENDERECOS> PES_ENDERECOS { get; set; }
        public virtual DbSet<PES_ESTADO_CIVIL> PES_ESTADO_CIVIL { get; set; }
        public virtual DbSet<PES_FAMILIARES_GRUPOS> PES_FAMILIARES_GRUPOS { get; set; }
        public virtual DbSet<PES_IDENTIFICACAO> PES_IDENTIFICACAO { get; set; }
        public virtual DbSet<PES_IDENTIFICACAO_LOCAL_EM> PES_IDENTIFICACAO_LOCAL_EM { get; set; }
        public virtual DbSet<PES_NACIONALIDADE> PES_NACIONALIDADE { get; set; }
        public virtual DbSet<PES_NATURALIDADE> PES_NATURALIDADE { get; set; }
        public virtual DbSet<PES_PESSOAS> PES_PESSOAS { get; set; }
        public virtual DbSet<PES_PESSOAS_CARACT> PES_PESSOAS_CARACT { get; set; }
        public virtual DbSet<PES_PESSOAS_CARACT_DEFICIENCIA> PES_PESSOAS_CARACT_DEFICIENCIA { get; set; }
        public virtual DbSet<PES_PESSOAS_CARACT_GRAU_DEF> PES_PESSOAS_CARACT_GRAU_DEF { get; set; }
        public virtual DbSet<PES_PESSOAS_CARACT_TIPO_DEF> PES_PESSOAS_CARACT_TIPO_DEF { get; set; }
        public virtual DbSet<PES_PESSOAS_CARACT_TIPO_SANG> PES_PESSOAS_CARACT_TIPO_SANG { get; set; }
        public virtual DbSet<PES_PESSOAS_FAM> PES_PESSOAS_FAM { get; set; }
        public virtual DbSet<PES_PESSOAS_FAM_CONTACTOS> PES_PESSOAS_FAM_CONTACTOS { get; set; }
        public virtual DbSet<PES_PESSOAS_FAM_ENDERECOS> PES_PESSOAS_FAM_ENDERECOS { get; set; }
        public virtual DbSet<PES_PESSOAS_PROFISSOES> PES_PESSOAS_PROFISSOES { get; set; }
        public virtual DbSet<PES_PROFISSOES> PES_PROFISSOES { get; set; }
        public virtual DbSet<PES_PROFISSOES_REGIME_TRABALHO> PES_PROFISSOES_REGIME_TRABALHO { get; set; }
        public virtual DbSet<PES_PROFISSOES_TIPO_CONTRACTO> PES_PROFISSOES_TIPO_CONTRACTO { get; set; }
        public virtual DbSet<PES_TIPO_ENDERECOS> PES_TIPO_ENDERECOS { get; set; }
        public virtual DbSet<PES_TIPO_IDENTIFICACAO> PES_TIPO_IDENTIFICACAO { get; set; }
        public virtual DbSet<UTILIZADORES> UTILIZADORES { get; set; }
        public virtual DbSet<UTILIZADORES_ACESSO_ATOMOS> UTILIZADORES_ACESSO_ATOMOS { get; set; }
        public virtual DbSet<UTILIZADORES_ACESSO_ATOMOS_GRUPOS> UTILIZADORES_ACESSO_ATOMOS_GRUPOS { get; set; }
        public virtual DbSet<UTILIZADORES_ACESSO_GRUPOS> UTILIZADORES_ACESSO_GRUPOS { get; set; }
        public virtual DbSet<UTILIZADORES_ACESSO_PERFIS> UTILIZADORES_ACESSO_PERFIS { get; set; }
        public virtual DbSet<UTILIZADORES_ACESSO_PERFIS_ATOMOS> UTILIZADORES_ACESSO_PERFIS_ATOMOS { get; set; }
        public virtual DbSet<UTILIZADORES_ACESSO_UTIL_GRUPOS> UTILIZADORES_ACESSO_UTIL_GRUPOS { get; set; }
        public virtual DbSet<UTILIZADORES_ACESSO_UTIL_PERFIS> UTILIZADORES_ACESSO_UTIL_PERFIS { get; set; }
        public virtual DbSet<UTILIZADORES_LOGIN_LOGS> UTILIZADORES_LOGIN_LOGS { get; set; }
    }
}
