//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestreino
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GESTREINO_Entities : DbContext
    {
        public GESTREINO_Entities()
            : base("name=GESTREINO_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GRL_ANO_LECTIVO> GRL_ANO_LECTIVO { get; set; }
        public virtual DbSet<GRL_ARQUIVOS> GRL_ARQUIVOS { get; set; }
        public virtual DbSet<GRL_ARQUIVOS_TIPO_DOCS> GRL_ARQUIVOS_TIPO_DOCS { get; set; }
        public virtual DbSet<GRL_ENDERECO_CIDADE> GRL_ENDERECO_CIDADE { get; set; }
        public virtual DbSet<GRL_ENDERECO_MUN_DISTR> GRL_ENDERECO_MUN_DISTR { get; set; }
        public virtual DbSet<GRL_ENDERECO_PAIS> GRL_ENDERECO_PAIS { get; set; }
        public virtual DbSet<GRL_TOKENS> GRL_TOKENS { get; set; }
        public virtual DbSet<GRL_TOKENS_TIPOS> GRL_TOKENS_TIPOS { get; set; }
        public virtual DbSet<INST_APLICACAO_ARQUIVOS> INST_APLICACAO_ARQUIVOS { get; set; }
        public virtual DbSet<INST_APLICACAO_CONTACTOS> INST_APLICACAO_CONTACTOS { get; set; }
        public virtual DbSet<INST_APLICACAO_ENDERECOS> INST_APLICACAO_ENDERECOS { get; set; }
        public virtual DbSet<PES_ARQUIVOS> PES_ARQUIVOS { get; set; }
        public virtual DbSet<PES_ENDERECOS> PES_ENDERECOS { get; set; }
        public virtual DbSet<PES_ESTADO_CIVIL> PES_ESTADO_CIVIL { get; set; }
        public virtual DbSet<PES_FAMILIARES_GRUPOS> PES_FAMILIARES_GRUPOS { get; set; }
        public virtual DbSet<PES_IDENTIFICACAO> PES_IDENTIFICACAO { get; set; }
        public virtual DbSet<PES_IDENTIFICACAO_LOCAL_EM> PES_IDENTIFICACAO_LOCAL_EM { get; set; }
        public virtual DbSet<PES_NACIONALIDADE> PES_NACIONALIDADE { get; set; }
        public virtual DbSet<PES_NATURALIDADE> PES_NATURALIDADE { get; set; }
        public virtual DbSet<PES_PESSOAS_CARACT_DEFICIENCIA> PES_PESSOAS_CARACT_DEFICIENCIA { get; set; }
        public virtual DbSet<PES_PESSOAS_CARACT_TIPO_DEF> PES_PESSOAS_CARACT_TIPO_DEF { get; set; }
        public virtual DbSet<PES_PESSOAS_CARACT_TIPO_SANG> PES_PESSOAS_CARACT_TIPO_SANG { get; set; }
        public virtual DbSet<PES_PESSOAS_FAM> PES_PESSOAS_FAM { get; set; }
        public virtual DbSet<PES_PESSOAS_FAM_CONTACTOS> PES_PESSOAS_FAM_CONTACTOS { get; set; }
        public virtual DbSet<PES_PESSOAS_FAM_ENDERECOS> PES_PESSOAS_FAM_ENDERECOS { get; set; }
        public virtual DbSet<PES_PESSOAS_PROFISSOES> PES_PESSOAS_PROFISSOES { get; set; }
        public virtual DbSet<PES_PROFISSOES> PES_PROFISSOES { get; set; }
        public virtual DbSet<PES_PROFISSOES_REGIME_TRABALHO> PES_PROFISSOES_REGIME_TRABALHO { get; set; }
        public virtual DbSet<PES_PROFISSOES_TIPO_CONTRACTO> PES_PROFISSOES_TIPO_CONTRACTO { get; set; }
        public virtual DbSet<PES_TIPO_ENDERECOS> PES_TIPO_ENDERECOS { get; set; }
        public virtual DbSet<PES_TIPO_IDENTIFICACAO> PES_TIPO_IDENTIFICACAO { get; set; }
        public virtual DbSet<UTILIZADORES> UTILIZADORES { get; set; }
        public virtual DbSet<UTILIZADORES_ACESSO_ATOMOS_GRUPOS> UTILIZADORES_ACESSO_ATOMOS_GRUPOS { get; set; }
        public virtual DbSet<UTILIZADORES_ACESSO_GRUPOS> UTILIZADORES_ACESSO_GRUPOS { get; set; }
        public virtual DbSet<UTILIZADORES_ACESSO_PERFIS> UTILIZADORES_ACESSO_PERFIS { get; set; }
        public virtual DbSet<UTILIZADORES_ACESSO_PERFIS_ATOMOS> UTILIZADORES_ACESSO_PERFIS_ATOMOS { get; set; }
        public virtual DbSet<UTILIZADORES_ACESSO_UTIL_GRUPOS> UTILIZADORES_ACESSO_UTIL_GRUPOS { get; set; }
        public virtual DbSet<UTILIZADORES_ACESSO_UTIL_PERFIS> UTILIZADORES_ACESSO_UTIL_PERFIS { get; set; }
        public virtual DbSet<UTILIZADORES_LOGIN_LOGS> UTILIZADORES_LOGIN_LOGS { get; set; }
        public virtual DbSet<UTILIZADORES_LOGIN_PASSWORD_TENT> UTILIZADORES_LOGIN_PASSWORD_TENT { get; set; }
        public virtual DbSet<INST_APLICACAO> INST_APLICACAO { get; set; }
        public virtual DbSet<PES_PESSOAS> PES_PESSOAS { get; set; }
        public virtual DbSet<UTILIZADORES_ACESSO_ATOMOS> UTILIZADORES_ACESSO_ATOMOS { get; set; }
        public virtual DbSet<GRL_DEFINICOES> GRL_DEFINICOES { get; set; }
        public virtual DbSet<PES_CONTACTOS> PES_CONTACTOS { get; set; }
        public virtual DbSet<GT_DuracaoPlano> GT_DuracaoPlano { get; set; }
        public virtual DbSet<PES_PESSOAS_CARACT> PES_PESSOAS_CARACT { get; set; }
    
        public virtual ObjectResult<SP_UTILIZADORES_LOGIN_LOGS_Result> SP_UTILIZADORES_LOGIN_LOGS(Nullable<int> userId, string action)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_UTILIZADORES_LOGIN_LOGS_Result>("SP_UTILIZADORES_LOGIN_LOGS", userIdParameter, actionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_UTILIZADORES_LOGIN(Nullable<int> userId, Nullable<int> moduleId, string ipAddress, string macAddress, string host, string device, Nullable<decimal> lat, Nullable<decimal> @long, string url, string action)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var moduleIdParameter = moduleId.HasValue ?
                new ObjectParameter("ModuleId", moduleId) :
                new ObjectParameter("ModuleId", typeof(int));
    
            var ipAddressParameter = ipAddress != null ?
                new ObjectParameter("IpAddress", ipAddress) :
                new ObjectParameter("IpAddress", typeof(string));
    
            var macAddressParameter = macAddress != null ?
                new ObjectParameter("MacAddress", macAddress) :
                new ObjectParameter("MacAddress", typeof(string));
    
            var hostParameter = host != null ?
                new ObjectParameter("Host", host) :
                new ObjectParameter("Host", typeof(string));
    
            var deviceParameter = device != null ?
                new ObjectParameter("Device", device) :
                new ObjectParameter("Device", typeof(string));
    
            var latParameter = lat.HasValue ?
                new ObjectParameter("Lat", lat) :
                new ObjectParameter("Lat", typeof(decimal));
    
            var longParameter = @long.HasValue ?
                new ObjectParameter("Long", @long) :
                new ObjectParameter("Long", typeof(decimal));
    
            var urlParameter = url != null ?
                new ObjectParameter("Url", url) :
                new ObjectParameter("Url", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_UTILIZADORES_LOGIN", userIdParameter, moduleIdParameter, ipAddressParameter, macAddressParameter, hostParameter, deviceParameter, latParameter, longParameter, urlParameter, actionParameter);
        }
    
        public virtual ObjectResult<SP_UTILIZADORES_ENT_UTILIZADORES_Result> SP_UTILIZADORES_ENT_UTILIZADORES(Nullable<int> id, Nullable<int> subGroupId, Nullable<int> profileId, string login, string nome, Nullable<decimal> telefone, string email, string senha, string salt, Nullable<bool> activo, Nullable<System.DateTime> dataAct, Nullable<System.DateTime> dataDesact, Nullable<bool> validada, Nullable<int> userInsercaoId, string action)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var subGroupIdParameter = subGroupId.HasValue ?
                new ObjectParameter("SubGroupId", subGroupId) :
                new ObjectParameter("SubGroupId", typeof(int));
    
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            var loginParameter = login != null ?
                new ObjectParameter("login", login) :
                new ObjectParameter("login", typeof(string));
    
            var nomeParameter = nome != null ?
                new ObjectParameter("Nome", nome) :
                new ObjectParameter("Nome", typeof(string));
    
            var telefoneParameter = telefone.HasValue ?
                new ObjectParameter("Telefone", telefone) :
                new ObjectParameter("Telefone", typeof(decimal));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var senhaParameter = senha != null ?
                new ObjectParameter("Senha", senha) :
                new ObjectParameter("Senha", typeof(string));
    
            var saltParameter = salt != null ?
                new ObjectParameter("Salt", salt) :
                new ObjectParameter("Salt", typeof(string));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("Activo", activo) :
                new ObjectParameter("Activo", typeof(bool));
    
            var dataActParameter = dataAct.HasValue ?
                new ObjectParameter("DataAct", dataAct) :
                new ObjectParameter("DataAct", typeof(System.DateTime));
    
            var dataDesactParameter = dataDesact.HasValue ?
                new ObjectParameter("DataDesact", dataDesact) :
                new ObjectParameter("DataDesact", typeof(System.DateTime));
    
            var validadaParameter = validada.HasValue ?
                new ObjectParameter("Validada", validada) :
                new ObjectParameter("Validada", typeof(bool));
    
            var userInsercaoIdParameter = userInsercaoId.HasValue ?
                new ObjectParameter("UserInsercaoId", userInsercaoId) :
                new ObjectParameter("UserInsercaoId", typeof(int));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_UTILIZADORES_ENT_UTILIZADORES_Result>("SP_UTILIZADORES_ENT_UTILIZADORES", idParameter, subGroupIdParameter, profileIdParameter, loginParameter, nomeParameter, telefoneParameter, emailParameter, senhaParameter, saltParameter, activoParameter, dataActParameter, dataDesactParameter, validadaParameter, userInsercaoIdParameter, actionParameter);
        }
    
        public virtual ObjectResult<SP_UTILIZADORES_ENT_ATOMOS_Result> SP_UTILIZADORES_ENT_ATOMOS(Nullable<int> id, string nome, string descricao, Nullable<int> userInsercaoId, string action)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var nomeParameter = nome != null ?
                new ObjectParameter("Nome", nome) :
                new ObjectParameter("Nome", typeof(string));
    
            var descricaoParameter = descricao != null ?
                new ObjectParameter("Descricao", descricao) :
                new ObjectParameter("Descricao", typeof(string));
    
            var userInsercaoIdParameter = userInsercaoId.HasValue ?
                new ObjectParameter("UserInsercaoId", userInsercaoId) :
                new ObjectParameter("UserInsercaoId", typeof(int));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_UTILIZADORES_ENT_ATOMOS_Result>("SP_UTILIZADORES_ENT_ATOMOS", idParameter, nomeParameter, descricaoParameter, userInsercaoIdParameter, actionParameter);
        }
    
        public virtual ObjectResult<SP_UTILIZADORES_ENT_GRUPOS_Result> SP_UTILIZADORES_ENT_GRUPOS(Nullable<int> id, string sigla, string nome, string descricao, Nullable<int> userInsercaoId, string action)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var siglaParameter = sigla != null ?
                new ObjectParameter("Sigla", sigla) :
                new ObjectParameter("Sigla", typeof(string));
    
            var nomeParameter = nome != null ?
                new ObjectParameter("Nome", nome) :
                new ObjectParameter("Nome", typeof(string));
    
            var descricaoParameter = descricao != null ?
                new ObjectParameter("Descricao", descricao) :
                new ObjectParameter("Descricao", typeof(string));
    
            var userInsercaoIdParameter = userInsercaoId.HasValue ?
                new ObjectParameter("UserInsercaoId", userInsercaoId) :
                new ObjectParameter("UserInsercaoId", typeof(int));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_UTILIZADORES_ENT_GRUPOS_Result>("SP_UTILIZADORES_ENT_GRUPOS", idParameter, siglaParameter, nomeParameter, descricaoParameter, userInsercaoIdParameter, actionParameter);
        }
    
        public virtual ObjectResult<SP_UTILIZADORES_ENT_PERFIS_Result> SP_UTILIZADORES_ENT_PERFIS(Nullable<int> id, string nome, string descricao, Nullable<int> userInsercaoId, string action)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var nomeParameter = nome != null ?
                new ObjectParameter("Nome", nome) :
                new ObjectParameter("Nome", typeof(string));
    
            var descricaoParameter = descricao != null ?
                new ObjectParameter("Descricao", descricao) :
                new ObjectParameter("Descricao", typeof(string));
    
            var userInsercaoIdParameter = userInsercaoId.HasValue ?
                new ObjectParameter("UserInsercaoId", userInsercaoId) :
                new ObjectParameter("UserInsercaoId", typeof(int));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_UTILIZADORES_ENT_PERFIS_Result>("SP_UTILIZADORES_ENT_PERFIS", idParameter, nomeParameter, descricaoParameter, userInsercaoIdParameter, actionParameter);
        }
    
        public virtual ObjectResult<SP_UTILIZADORES_ENT_ATOMOS_GRUPOS_Result> SP_UTILIZADORES_ENT_ATOMOS_GRUPOS(Nullable<int> id, Nullable<int> groupId, Nullable<int> atomId, Nullable<int> userInsercaoId, string action)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(int));
    
            var atomIdParameter = atomId.HasValue ?
                new ObjectParameter("AtomId", atomId) :
                new ObjectParameter("AtomId", typeof(int));
    
            var userInsercaoIdParameter = userInsercaoId.HasValue ?
                new ObjectParameter("UserInsercaoId", userInsercaoId) :
                new ObjectParameter("UserInsercaoId", typeof(int));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_UTILIZADORES_ENT_ATOMOS_GRUPOS_Result>("SP_UTILIZADORES_ENT_ATOMOS_GRUPOS", idParameter, groupIdParameter, atomIdParameter, userInsercaoIdParameter, actionParameter);
        }
    
        public virtual ObjectResult<SP_UTILIZADORES_ENT_GRUPOS_UTILIZADORES_Result> SP_UTILIZADORES_ENT_GRUPOS_UTILIZADORES(Nullable<int> id, Nullable<int> groupId, Nullable<int> userId, Nullable<int> userInsercaoId, string action)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(int));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var userInsercaoIdParameter = userInsercaoId.HasValue ?
                new ObjectParameter("UserInsercaoId", userInsercaoId) :
                new ObjectParameter("UserInsercaoId", typeof(int));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_UTILIZADORES_ENT_GRUPOS_UTILIZADORES_Result>("SP_UTILIZADORES_ENT_GRUPOS_UTILIZADORES", idParameter, groupIdParameter, userIdParameter, userInsercaoIdParameter, actionParameter);
        }
    
        public virtual ObjectResult<SP_UTILIZADORES_ENT_PERFIS_ATOMOS_Result> SP_UTILIZADORES_ENT_PERFIS_ATOMOS(Nullable<int> id, Nullable<int> profileId, Nullable<int> atomId, Nullable<int> userInsercaoId, string action)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            var atomIdParameter = atomId.HasValue ?
                new ObjectParameter("AtomId", atomId) :
                new ObjectParameter("AtomId", typeof(int));
    
            var userInsercaoIdParameter = userInsercaoId.HasValue ?
                new ObjectParameter("UserInsercaoId", userInsercaoId) :
                new ObjectParameter("UserInsercaoId", typeof(int));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_UTILIZADORES_ENT_PERFIS_ATOMOS_Result>("SP_UTILIZADORES_ENT_PERFIS_ATOMOS", idParameter, profileIdParameter, atomIdParameter, userInsercaoIdParameter, actionParameter);
        }
    
        public virtual ObjectResult<SP_UTILIZADORES_ENT_UTILIZADORES_PERFIS_Result> SP_UTILIZADORES_ENT_UTILIZADORES_PERFIS(Nullable<int> id, Nullable<int> profileId, Nullable<int> userId, Nullable<int> userInsercaoId, string action)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var userInsercaoIdParameter = userInsercaoId.HasValue ?
                new ObjectParameter("UserInsercaoId", userInsercaoId) :
                new ObjectParameter("UserInsercaoId", typeof(int));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_UTILIZADORES_ENT_UTILIZADORES_PERFIS_Result>("SP_UTILIZADORES_ENT_UTILIZADORES_PERFIS", idParameter, profileIdParameter, userIdParameter, userInsercaoIdParameter, actionParameter);
        }
    
        public virtual ObjectResult<SP_GRL_ENT_END_CIDADE_Result> SP_GRL_ENT_END_CIDADE(Nullable<int> id, string sigla, string nome, Nullable<int> paisId, Nullable<int> userInsercaoId, string action)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var siglaParameter = sigla != null ?
                new ObjectParameter("Sigla", sigla) :
                new ObjectParameter("Sigla", typeof(string));
    
            var nomeParameter = nome != null ?
                new ObjectParameter("Nome", nome) :
                new ObjectParameter("Nome", typeof(string));
    
            var paisIdParameter = paisId.HasValue ?
                new ObjectParameter("PaisId", paisId) :
                new ObjectParameter("PaisId", typeof(int));
    
            var userInsercaoIdParameter = userInsercaoId.HasValue ?
                new ObjectParameter("UserInsercaoId", userInsercaoId) :
                new ObjectParameter("UserInsercaoId", typeof(int));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GRL_ENT_END_CIDADE_Result>("SP_GRL_ENT_END_CIDADE", idParameter, siglaParameter, nomeParameter, paisIdParameter, userInsercaoIdParameter, actionParameter);
        }
    
        public virtual ObjectResult<SP_GRL_ENT_END_DISTR_Result> SP_GRL_ENT_END_DISTR(Nullable<int> id, string sigla, string nome, Nullable<int> cidadeId, Nullable<int> userInsercaoId, string action)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var siglaParameter = sigla != null ?
                new ObjectParameter("Sigla", sigla) :
                new ObjectParameter("Sigla", typeof(string));
    
            var nomeParameter = nome != null ?
                new ObjectParameter("Nome", nome) :
                new ObjectParameter("Nome", typeof(string));
    
            var cidadeIdParameter = cidadeId.HasValue ?
                new ObjectParameter("CidadeId", cidadeId) :
                new ObjectParameter("CidadeId", typeof(int));
    
            var userInsercaoIdParameter = userInsercaoId.HasValue ?
                new ObjectParameter("UserInsercaoId", userInsercaoId) :
                new ObjectParameter("UserInsercaoId", typeof(int));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GRL_ENT_END_DISTR_Result>("SP_GRL_ENT_END_DISTR", idParameter, siglaParameter, nomeParameter, cidadeIdParameter, userInsercaoIdParameter, actionParameter);
        }
    
        public virtual ObjectResult<SP_GRL_ENT_END_PAIS_Result> SP_GRL_ENT_END_PAIS(Nullable<int> id, string sigla, string nome, Nullable<int> codigo, string indicativo, string mas, string fem, Nullable<int> userInsercaoId, string action)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var siglaParameter = sigla != null ?
                new ObjectParameter("Sigla", sigla) :
                new ObjectParameter("Sigla", typeof(string));
    
            var nomeParameter = nome != null ?
                new ObjectParameter("Nome", nome) :
                new ObjectParameter("Nome", typeof(string));
    
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(int));
    
            var indicativoParameter = indicativo != null ?
                new ObjectParameter("Indicativo", indicativo) :
                new ObjectParameter("Indicativo", typeof(string));
    
            var masParameter = mas != null ?
                new ObjectParameter("Mas", mas) :
                new ObjectParameter("Mas", typeof(string));
    
            var femParameter = fem != null ?
                new ObjectParameter("Fem", fem) :
                new ObjectParameter("Fem", typeof(string));
    
            var userInsercaoIdParameter = userInsercaoId.HasValue ?
                new ObjectParameter("UserInsercaoId", userInsercaoId) :
                new ObjectParameter("UserInsercaoId", typeof(int));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GRL_ENT_END_PAIS_Result>("SP_GRL_ENT_END_PAIS", idParameter, siglaParameter, nomeParameter, codigoParameter, indicativoParameter, masParameter, femParameter, userInsercaoIdParameter, actionParameter);
        }
    
        public virtual ObjectResult<SP_GRL_ENT_TIPODOC_Result> SP_GRL_ENT_TIPODOC(Nullable<int> id, string sigla, string nome, Nullable<int> userInsercaoId, string action)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var siglaParameter = sigla != null ?
                new ObjectParameter("Sigla", sigla) :
                new ObjectParameter("Sigla", typeof(string));
    
            var nomeParameter = nome != null ?
                new ObjectParameter("Nome", nome) :
                new ObjectParameter("Nome", typeof(string));
    
            var userInsercaoIdParameter = userInsercaoId.HasValue ?
                new ObjectParameter("UserInsercaoId", userInsercaoId) :
                new ObjectParameter("UserInsercaoId", typeof(int));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GRL_ENT_TIPODOC_Result>("SP_GRL_ENT_TIPODOC", idParameter, siglaParameter, nomeParameter, userInsercaoIdParameter, actionParameter);
        }
    
        public virtual ObjectResult<SP_GRL_ENT_TIPOTOKEN_Result> SP_GRL_ENT_TIPOTOKEN(Nullable<int> id, string nome, Nullable<int> userInsercaoId, string action)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var nomeParameter = nome != null ?
                new ObjectParameter("Nome", nome) :
                new ObjectParameter("Nome", typeof(string));
    
            var userInsercaoIdParameter = userInsercaoId.HasValue ?
                new ObjectParameter("UserInsercaoId", userInsercaoId) :
                new ObjectParameter("UserInsercaoId", typeof(int));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GRL_ENT_TIPOTOKEN_Result>("SP_GRL_ENT_TIPOTOKEN", idParameter, nomeParameter, userInsercaoIdParameter, actionParameter);
        }
    
        public virtual ObjectResult<SP_INST_APLICACAO_Result> SP_INST_APLICACAO(Nullable<int> id, string sigla, string nome, string nIF, Nullable<decimal> telefone, Nullable<decimal> telefoneAlternativo, Nullable<decimal> fax, string email, string codigoPostal, string uRL, Nullable<int> numero, string rua, string morada, Nullable<int> paisId, Nullable<int> cidadeId, Nullable<int> munId, Nullable<int> userInsercaoId, string action)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var siglaParameter = sigla != null ?
                new ObjectParameter("Sigla", sigla) :
                new ObjectParameter("Sigla", typeof(string));
    
            var nomeParameter = nome != null ?
                new ObjectParameter("Nome", nome) :
                new ObjectParameter("Nome", typeof(string));
    
            var nIFParameter = nIF != null ?
                new ObjectParameter("NIF", nIF) :
                new ObjectParameter("NIF", typeof(string));
    
            var telefoneParameter = telefone.HasValue ?
                new ObjectParameter("Telefone", telefone) :
                new ObjectParameter("Telefone", typeof(decimal));
    
            var telefoneAlternativoParameter = telefoneAlternativo.HasValue ?
                new ObjectParameter("TelefoneAlternativo", telefoneAlternativo) :
                new ObjectParameter("TelefoneAlternativo", typeof(decimal));
    
            var faxParameter = fax.HasValue ?
                new ObjectParameter("Fax", fax) :
                new ObjectParameter("Fax", typeof(decimal));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var codigoPostalParameter = codigoPostal != null ?
                new ObjectParameter("CodigoPostal", codigoPostal) :
                new ObjectParameter("CodigoPostal", typeof(string));
    
            var uRLParameter = uRL != null ?
                new ObjectParameter("URL", uRL) :
                new ObjectParameter("URL", typeof(string));
    
            var numeroParameter = numero.HasValue ?
                new ObjectParameter("Numero", numero) :
                new ObjectParameter("Numero", typeof(int));
    
            var ruaParameter = rua != null ?
                new ObjectParameter("Rua", rua) :
                new ObjectParameter("Rua", typeof(string));
    
            var moradaParameter = morada != null ?
                new ObjectParameter("Morada", morada) :
                new ObjectParameter("Morada", typeof(string));
    
            var paisIdParameter = paisId.HasValue ?
                new ObjectParameter("PaisId", paisId) :
                new ObjectParameter("PaisId", typeof(int));
    
            var cidadeIdParameter = cidadeId.HasValue ?
                new ObjectParameter("CidadeId", cidadeId) :
                new ObjectParameter("CidadeId", typeof(int));
    
            var munIdParameter = munId.HasValue ?
                new ObjectParameter("MunId", munId) :
                new ObjectParameter("MunId", typeof(int));
    
            var userInsercaoIdParameter = userInsercaoId.HasValue ?
                new ObjectParameter("UserInsercaoId", userInsercaoId) :
                new ObjectParameter("UserInsercaoId", typeof(int));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_INST_APLICACAO_Result>("SP_INST_APLICACAO", idParameter, siglaParameter, nomeParameter, nIFParameter, telefoneParameter, telefoneAlternativoParameter, faxParameter, emailParameter, codigoPostalParameter, uRLParameter, numeroParameter, ruaParameter, moradaParameter, paisIdParameter, cidadeIdParameter, munIdParameter, userInsercaoIdParameter, actionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_PES_ENT_PESSOAS_CARACT(Nullable<int> id, Nullable<int> pesId, Nullable<int> tipoSangueId, Nullable<decimal> altura, Nullable<decimal> peso, Nullable<int> fCREPOUSO, Nullable<int> fCMAXIMO, Nullable<int> tASISTOLICA, Nullable<int> tADISTOLICA, Nullable<int> mASSAGORDA, Nullable<int> vO2, Nullable<int> gT_DuracaoPlano_ID, Nullable<int> iMC, Nullable<decimal> fCTreino1, Nullable<decimal> fCTreino2, Nullable<decimal> fCTreino3, Nullable<decimal> fCTreino4, Nullable<decimal> fCTreino5, Nullable<decimal> fCTreino6, Nullable<decimal> fCTreino7, Nullable<decimal> fCTreino8, Nullable<decimal> fCTreino9, Nullable<decimal> fCTreino10, Nullable<bool> fR_ht, Nullable<bool> fR_tb, Nullable<bool> fR_hl, Nullable<bool> fR_ob, Nullable<bool> fR_db, Nullable<bool> fR_in, Nullable<bool> fR_he, Nullable<bool> fR_ec, Nullable<bool> fR_ot, Nullable<bool> oB_ac, Nullable<bool> oB_cp, Nullable<bool> oB_pi, Nullable<bool> oB_tp, Nullable<bool> oB_am, Nullable<bool> oB_be, Nullable<bool> oB_to, Nullable<bool> oB_ot, string observacoes, Nullable<int> userInsercaoId, string action)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var pesIdParameter = pesId.HasValue ?
                new ObjectParameter("PesId", pesId) :
                new ObjectParameter("PesId", typeof(int));
    
            var tipoSangueIdParameter = tipoSangueId.HasValue ?
                new ObjectParameter("TipoSangueId", tipoSangueId) :
                new ObjectParameter("TipoSangueId", typeof(int));
    
            var alturaParameter = altura.HasValue ?
                new ObjectParameter("Altura", altura) :
                new ObjectParameter("Altura", typeof(decimal));
    
            var pesoParameter = peso.HasValue ?
                new ObjectParameter("Peso", peso) :
                new ObjectParameter("Peso", typeof(decimal));
    
            var fCREPOUSOParameter = fCREPOUSO.HasValue ?
                new ObjectParameter("FCREPOUSO", fCREPOUSO) :
                new ObjectParameter("FCREPOUSO", typeof(int));
    
            var fCMAXIMOParameter = fCMAXIMO.HasValue ?
                new ObjectParameter("FCMAXIMO", fCMAXIMO) :
                new ObjectParameter("FCMAXIMO", typeof(int));
    
            var tASISTOLICAParameter = tASISTOLICA.HasValue ?
                new ObjectParameter("TASISTOLICA", tASISTOLICA) :
                new ObjectParameter("TASISTOLICA", typeof(int));
    
            var tADISTOLICAParameter = tADISTOLICA.HasValue ?
                new ObjectParameter("TADISTOLICA", tADISTOLICA) :
                new ObjectParameter("TADISTOLICA", typeof(int));
    
            var mASSAGORDAParameter = mASSAGORDA.HasValue ?
                new ObjectParameter("MASSAGORDA", mASSAGORDA) :
                new ObjectParameter("MASSAGORDA", typeof(int));
    
            var vO2Parameter = vO2.HasValue ?
                new ObjectParameter("VO2", vO2) :
                new ObjectParameter("VO2", typeof(int));
    
            var gT_DuracaoPlano_IDParameter = gT_DuracaoPlano_ID.HasValue ?
                new ObjectParameter("GT_DuracaoPlano_ID", gT_DuracaoPlano_ID) :
                new ObjectParameter("GT_DuracaoPlano_ID", typeof(int));
    
            var iMCParameter = iMC.HasValue ?
                new ObjectParameter("IMC", iMC) :
                new ObjectParameter("IMC", typeof(int));
    
            var fCTreino1Parameter = fCTreino1.HasValue ?
                new ObjectParameter("FCTreino1", fCTreino1) :
                new ObjectParameter("FCTreino1", typeof(decimal));
    
            var fCTreino2Parameter = fCTreino2.HasValue ?
                new ObjectParameter("FCTreino2", fCTreino2) :
                new ObjectParameter("FCTreino2", typeof(decimal));
    
            var fCTreino3Parameter = fCTreino3.HasValue ?
                new ObjectParameter("FCTreino3", fCTreino3) :
                new ObjectParameter("FCTreino3", typeof(decimal));
    
            var fCTreino4Parameter = fCTreino4.HasValue ?
                new ObjectParameter("FCTreino4", fCTreino4) :
                new ObjectParameter("FCTreino4", typeof(decimal));
    
            var fCTreino5Parameter = fCTreino5.HasValue ?
                new ObjectParameter("FCTreino5", fCTreino5) :
                new ObjectParameter("FCTreino5", typeof(decimal));
    
            var fCTreino6Parameter = fCTreino6.HasValue ?
                new ObjectParameter("FCTreino6", fCTreino6) :
                new ObjectParameter("FCTreino6", typeof(decimal));
    
            var fCTreino7Parameter = fCTreino7.HasValue ?
                new ObjectParameter("FCTreino7", fCTreino7) :
                new ObjectParameter("FCTreino7", typeof(decimal));
    
            var fCTreino8Parameter = fCTreino8.HasValue ?
                new ObjectParameter("FCTreino8", fCTreino8) :
                new ObjectParameter("FCTreino8", typeof(decimal));
    
            var fCTreino9Parameter = fCTreino9.HasValue ?
                new ObjectParameter("FCTreino9", fCTreino9) :
                new ObjectParameter("FCTreino9", typeof(decimal));
    
            var fCTreino10Parameter = fCTreino10.HasValue ?
                new ObjectParameter("FCTreino10", fCTreino10) :
                new ObjectParameter("FCTreino10", typeof(decimal));
    
            var fR_htParameter = fR_ht.HasValue ?
                new ObjectParameter("FR_ht", fR_ht) :
                new ObjectParameter("FR_ht", typeof(bool));
    
            var fR_tbParameter = fR_tb.HasValue ?
                new ObjectParameter("FR_tb", fR_tb) :
                new ObjectParameter("FR_tb", typeof(bool));
    
            var fR_hlParameter = fR_hl.HasValue ?
                new ObjectParameter("FR_hl", fR_hl) :
                new ObjectParameter("FR_hl", typeof(bool));
    
            var fR_obParameter = fR_ob.HasValue ?
                new ObjectParameter("FR_ob", fR_ob) :
                new ObjectParameter("FR_ob", typeof(bool));
    
            var fR_dbParameter = fR_db.HasValue ?
                new ObjectParameter("FR_db", fR_db) :
                new ObjectParameter("FR_db", typeof(bool));
    
            var fR_inParameter = fR_in.HasValue ?
                new ObjectParameter("FR_in", fR_in) :
                new ObjectParameter("FR_in", typeof(bool));
    
            var fR_heParameter = fR_he.HasValue ?
                new ObjectParameter("FR_he", fR_he) :
                new ObjectParameter("FR_he", typeof(bool));
    
            var fR_ecParameter = fR_ec.HasValue ?
                new ObjectParameter("FR_ec", fR_ec) :
                new ObjectParameter("FR_ec", typeof(bool));
    
            var fR_otParameter = fR_ot.HasValue ?
                new ObjectParameter("FR_ot", fR_ot) :
                new ObjectParameter("FR_ot", typeof(bool));
    
            var oB_acParameter = oB_ac.HasValue ?
                new ObjectParameter("OB_ac", oB_ac) :
                new ObjectParameter("OB_ac", typeof(bool));
    
            var oB_cpParameter = oB_cp.HasValue ?
                new ObjectParameter("OB_cp", oB_cp) :
                new ObjectParameter("OB_cp", typeof(bool));
    
            var oB_piParameter = oB_pi.HasValue ?
                new ObjectParameter("OB_pi", oB_pi) :
                new ObjectParameter("OB_pi", typeof(bool));
    
            var oB_tpParameter = oB_tp.HasValue ?
                new ObjectParameter("OB_tp", oB_tp) :
                new ObjectParameter("OB_tp", typeof(bool));
    
            var oB_amParameter = oB_am.HasValue ?
                new ObjectParameter("OB_am", oB_am) :
                new ObjectParameter("OB_am", typeof(bool));
    
            var oB_beParameter = oB_be.HasValue ?
                new ObjectParameter("OB_be", oB_be) :
                new ObjectParameter("OB_be", typeof(bool));
    
            var oB_toParameter = oB_to.HasValue ?
                new ObjectParameter("OB_to", oB_to) :
                new ObjectParameter("OB_to", typeof(bool));
    
            var oB_otParameter = oB_ot.HasValue ?
                new ObjectParameter("OB_ot", oB_ot) :
                new ObjectParameter("OB_ot", typeof(bool));
    
            var observacoesParameter = observacoes != null ?
                new ObjectParameter("Observacoes", observacoes) :
                new ObjectParameter("Observacoes", typeof(string));
    
            var userInsercaoIdParameter = userInsercaoId.HasValue ?
                new ObjectParameter("UserInsercaoId", userInsercaoId) :
                new ObjectParameter("UserInsercaoId", typeof(int));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_PES_ENT_PESSOAS_CARACT", idParameter, pesIdParameter, tipoSangueIdParameter, alturaParameter, pesoParameter, fCREPOUSOParameter, fCMAXIMOParameter, tASISTOLICAParameter, tADISTOLICAParameter, mASSAGORDAParameter, vO2Parameter, gT_DuracaoPlano_IDParameter, iMCParameter, fCTreino1Parameter, fCTreino2Parameter, fCTreino3Parameter, fCTreino4Parameter, fCTreino5Parameter, fCTreino6Parameter, fCTreino7Parameter, fCTreino8Parameter, fCTreino9Parameter, fCTreino10Parameter, fR_htParameter, fR_tbParameter, fR_hlParameter, fR_obParameter, fR_dbParameter, fR_inParameter, fR_heParameter, fR_ecParameter, fR_otParameter, oB_acParameter, oB_cpParameter, oB_piParameter, oB_tpParameter, oB_amParameter, oB_beParameter, oB_toParameter, oB_otParameter, observacoesParameter, userInsercaoIdParameter, actionParameter);
        }
    
        public virtual ObjectResult<SP_PES_ENT_PESSOAS_Result> SP_PES_ENT_PESSOAS(Nullable<int> iD, string nome, string sexo, Nullable<System.DateTime> dataNascimento, Nullable<int> estadoCivilId, string nIF, string apresentacaoPessoal, Nullable<int> paisId, Nullable<int> cidadeId, Nullable<int> municipioId, Nullable<decimal> telefone, Nullable<decimal> telefoneAlternativo, Nullable<decimal> fax, string email, string codigoPostal, string url, Nullable<int> numero, Nullable<int> userId, string action)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var nomeParameter = nome != null ?
                new ObjectParameter("Nome", nome) :
                new ObjectParameter("Nome", typeof(string));
    
            var sexoParameter = sexo != null ?
                new ObjectParameter("Sexo", sexo) :
                new ObjectParameter("Sexo", typeof(string));
    
            var dataNascimentoParameter = dataNascimento.HasValue ?
                new ObjectParameter("DataNascimento", dataNascimento) :
                new ObjectParameter("DataNascimento", typeof(System.DateTime));
    
            var estadoCivilIdParameter = estadoCivilId.HasValue ?
                new ObjectParameter("EstadoCivilId", estadoCivilId) :
                new ObjectParameter("EstadoCivilId", typeof(int));
    
            var nIFParameter = nIF != null ?
                new ObjectParameter("NIF", nIF) :
                new ObjectParameter("NIF", typeof(string));
    
            var apresentacaoPessoalParameter = apresentacaoPessoal != null ?
                new ObjectParameter("ApresentacaoPessoal", apresentacaoPessoal) :
                new ObjectParameter("ApresentacaoPessoal", typeof(string));
    
            var paisIdParameter = paisId.HasValue ?
                new ObjectParameter("PaisId", paisId) :
                new ObjectParameter("PaisId", typeof(int));
    
            var cidadeIdParameter = cidadeId.HasValue ?
                new ObjectParameter("CidadeId", cidadeId) :
                new ObjectParameter("CidadeId", typeof(int));
    
            var municipioIdParameter = municipioId.HasValue ?
                new ObjectParameter("MunicipioId", municipioId) :
                new ObjectParameter("MunicipioId", typeof(int));
    
            var telefoneParameter = telefone.HasValue ?
                new ObjectParameter("Telefone", telefone) :
                new ObjectParameter("Telefone", typeof(decimal));
    
            var telefoneAlternativoParameter = telefoneAlternativo.HasValue ?
                new ObjectParameter("TelefoneAlternativo", telefoneAlternativo) :
                new ObjectParameter("TelefoneAlternativo", typeof(decimal));
    
            var faxParameter = fax.HasValue ?
                new ObjectParameter("Fax", fax) :
                new ObjectParameter("Fax", typeof(decimal));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var codigoPostalParameter = codigoPostal != null ?
                new ObjectParameter("CodigoPostal", codigoPostal) :
                new ObjectParameter("CodigoPostal", typeof(string));
    
            var urlParameter = url != null ?
                new ObjectParameter("Url", url) :
                new ObjectParameter("Url", typeof(string));
    
            var numeroParameter = numero.HasValue ?
                new ObjectParameter("Numero", numero) :
                new ObjectParameter("Numero", typeof(int));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PES_ENT_PESSOAS_Result>("SP_PES_ENT_PESSOAS", iDParameter, nomeParameter, sexoParameter, dataNascimentoParameter, estadoCivilIdParameter, nIFParameter, apresentacaoPessoalParameter, paisIdParameter, cidadeIdParameter, municipioIdParameter, telefoneParameter, telefoneAlternativoParameter, faxParameter, emailParameter, codigoPostalParameter, urlParameter, numeroParameter, userIdParameter, actionParameter);
        }
    
        public virtual ObjectResult<SP_PES_ENT_PESSOAS_ENDERECO_Result> SP_PES_ENT_PESSOAS_ENDERECO(Nullable<int> id, Nullable<int> pesId, Nullable<int> tipoEndereco, Nullable<bool> principal, Nullable<int> numero, string rua, string morada, Nullable<int> paisId, Nullable<int> cidadeId, Nullable<int> municipioId, Nullable<System.DateTime> dataInicio, Nullable<System.DateTime> dataFim, Nullable<int> userInsercaoId, string action)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var pesIdParameter = pesId.HasValue ?
                new ObjectParameter("PesId", pesId) :
                new ObjectParameter("PesId", typeof(int));
    
            var tipoEnderecoParameter = tipoEndereco.HasValue ?
                new ObjectParameter("TipoEndereco", tipoEndereco) :
                new ObjectParameter("TipoEndereco", typeof(int));
    
            var principalParameter = principal.HasValue ?
                new ObjectParameter("Principal", principal) :
                new ObjectParameter("Principal", typeof(bool));
    
            var numeroParameter = numero.HasValue ?
                new ObjectParameter("Numero", numero) :
                new ObjectParameter("Numero", typeof(int));
    
            var ruaParameter = rua != null ?
                new ObjectParameter("Rua", rua) :
                new ObjectParameter("Rua", typeof(string));
    
            var moradaParameter = morada != null ?
                new ObjectParameter("Morada", morada) :
                new ObjectParameter("Morada", typeof(string));
    
            var paisIdParameter = paisId.HasValue ?
                new ObjectParameter("PaisId", paisId) :
                new ObjectParameter("PaisId", typeof(int));
    
            var cidadeIdParameter = cidadeId.HasValue ?
                new ObjectParameter("CidadeId", cidadeId) :
                new ObjectParameter("CidadeId", typeof(int));
    
            var municipioIdParameter = municipioId.HasValue ?
                new ObjectParameter("MunicipioId", municipioId) :
                new ObjectParameter("MunicipioId", typeof(int));
    
            var dataInicioParameter = dataInicio.HasValue ?
                new ObjectParameter("DataInicio", dataInicio) :
                new ObjectParameter("DataInicio", typeof(System.DateTime));
    
            var dataFimParameter = dataFim.HasValue ?
                new ObjectParameter("DataFim", dataFim) :
                new ObjectParameter("DataFim", typeof(System.DateTime));
    
            var userInsercaoIdParameter = userInsercaoId.HasValue ?
                new ObjectParameter("UserInsercaoId", userInsercaoId) :
                new ObjectParameter("UserInsercaoId", typeof(int));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PES_ENT_PESSOAS_ENDERECO_Result>("SP_PES_ENT_PESSOAS_ENDERECO", idParameter, pesIdParameter, tipoEnderecoParameter, principalParameter, numeroParameter, ruaParameter, moradaParameter, paisIdParameter, cidadeIdParameter, municipioIdParameter, dataInicioParameter, dataFimParameter, userInsercaoIdParameter, actionParameter);
        }
    
        public virtual ObjectResult<SP_PES_ENT_PESSOAS_DEFICIENCIA_Result> SP_PES_ENT_PESSOAS_DEFICIENCIA(Nullable<int> id, Nullable<int> pesId, Nullable<int> deficienciaId, Nullable<int> grauId, string descricao, Nullable<int> userInsercaoId, string action)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var pesIdParameter = pesId.HasValue ?
                new ObjectParameter("PesId", pesId) :
                new ObjectParameter("PesId", typeof(int));
    
            var deficienciaIdParameter = deficienciaId.HasValue ?
                new ObjectParameter("DeficienciaId", deficienciaId) :
                new ObjectParameter("DeficienciaId", typeof(int));
    
            var grauIdParameter = grauId.HasValue ?
                new ObjectParameter("GrauId", grauId) :
                new ObjectParameter("GrauId", typeof(int));
    
            var descricaoParameter = descricao != null ?
                new ObjectParameter("Descricao", descricao) :
                new ObjectParameter("Descricao", typeof(string));
    
            var userInsercaoIdParameter = userInsercaoId.HasValue ?
                new ObjectParameter("UserInsercaoId", userInsercaoId) :
                new ObjectParameter("UserInsercaoId", typeof(int));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PES_ENT_PESSOAS_DEFICIENCIA_Result>("SP_PES_ENT_PESSOAS_DEFICIENCIA", idParameter, pesIdParameter, deficienciaIdParameter, grauIdParameter, descricaoParameter, userInsercaoIdParameter, actionParameter);
        }
    
        public virtual ObjectResult<SP_PES_ENT_PESSOAS_PROFISSOES_Result> SP_PES_ENT_PESSOAS_PROFISSOES(Nullable<int> id, Nullable<int> pesId, Nullable<int> regimeId, Nullable<int> contractoId, Nullable<int> profissaoId, string empresa, Nullable<System.DateTime> dateIni, Nullable<System.DateTime> dateEnd, string descricao, Nullable<int> userInsercaoId, string action)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var pesIdParameter = pesId.HasValue ?
                new ObjectParameter("PesId", pesId) :
                new ObjectParameter("PesId", typeof(int));
    
            var regimeIdParameter = regimeId.HasValue ?
                new ObjectParameter("RegimeId", regimeId) :
                new ObjectParameter("RegimeId", typeof(int));
    
            var contractoIdParameter = contractoId.HasValue ?
                new ObjectParameter("ContractoId", contractoId) :
                new ObjectParameter("ContractoId", typeof(int));
    
            var profissaoIdParameter = profissaoId.HasValue ?
                new ObjectParameter("ProfissaoId", profissaoId) :
                new ObjectParameter("ProfissaoId", typeof(int));
    
            var empresaParameter = empresa != null ?
                new ObjectParameter("Empresa", empresa) :
                new ObjectParameter("Empresa", typeof(string));
    
            var dateIniParameter = dateIni.HasValue ?
                new ObjectParameter("DateIni", dateIni) :
                new ObjectParameter("DateIni", typeof(System.DateTime));
    
            var dateEndParameter = dateEnd.HasValue ?
                new ObjectParameter("DateEnd", dateEnd) :
                new ObjectParameter("DateEnd", typeof(System.DateTime));
    
            var descricaoParameter = descricao != null ?
                new ObjectParameter("Descricao", descricao) :
                new ObjectParameter("Descricao", typeof(string));
    
            var userInsercaoIdParameter = userInsercaoId.HasValue ?
                new ObjectParameter("UserInsercaoId", userInsercaoId) :
                new ObjectParameter("UserInsercaoId", typeof(int));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PES_ENT_PESSOAS_PROFISSOES_Result>("SP_PES_ENT_PESSOAS_PROFISSOES", idParameter, pesIdParameter, regimeIdParameter, contractoIdParameter, profissaoIdParameter, empresaParameter, dateIniParameter, dateEndParameter, descricaoParameter, userInsercaoIdParameter, actionParameter);
        }
    
        public virtual ObjectResult<SP_PES_ENT_PESSOAS_FAM_Result> SP_PES_ENT_PESSOAS_FAM(Nullable<int> id, Nullable<int> pesId, Nullable<int> grupoId, Nullable<int> profissaoId, string nome, Nullable<decimal> telefone, Nullable<decimal> telefoneAlternativo, Nullable<decimal> fax, string email, string uRl, Nullable<int> numero, string rua, string morada, Nullable<int> paisId, Nullable<int> cidadeId, Nullable<int> municipioId, Nullable<bool> isento, Nullable<int> userInsercaoId, string action)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var pesIdParameter = pesId.HasValue ?
                new ObjectParameter("PesId", pesId) :
                new ObjectParameter("PesId", typeof(int));
    
            var grupoIdParameter = grupoId.HasValue ?
                new ObjectParameter("GrupoId", grupoId) :
                new ObjectParameter("GrupoId", typeof(int));
    
            var profissaoIdParameter = profissaoId.HasValue ?
                new ObjectParameter("ProfissaoId", profissaoId) :
                new ObjectParameter("ProfissaoId", typeof(int));
    
            var nomeParameter = nome != null ?
                new ObjectParameter("Nome", nome) :
                new ObjectParameter("Nome", typeof(string));
    
            var telefoneParameter = telefone.HasValue ?
                new ObjectParameter("Telefone", telefone) :
                new ObjectParameter("Telefone", typeof(decimal));
    
            var telefoneAlternativoParameter = telefoneAlternativo.HasValue ?
                new ObjectParameter("TelefoneAlternativo", telefoneAlternativo) :
                new ObjectParameter("TelefoneAlternativo", typeof(decimal));
    
            var faxParameter = fax.HasValue ?
                new ObjectParameter("Fax", fax) :
                new ObjectParameter("Fax", typeof(decimal));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var uRlParameter = uRl != null ?
                new ObjectParameter("URl", uRl) :
                new ObjectParameter("URl", typeof(string));
    
            var numeroParameter = numero.HasValue ?
                new ObjectParameter("Numero", numero) :
                new ObjectParameter("Numero", typeof(int));
    
            var ruaParameter = rua != null ?
                new ObjectParameter("Rua", rua) :
                new ObjectParameter("Rua", typeof(string));
    
            var moradaParameter = morada != null ?
                new ObjectParameter("Morada", morada) :
                new ObjectParameter("Morada", typeof(string));
    
            var paisIdParameter = paisId.HasValue ?
                new ObjectParameter("PaisId", paisId) :
                new ObjectParameter("PaisId", typeof(int));
    
            var cidadeIdParameter = cidadeId.HasValue ?
                new ObjectParameter("CidadeId", cidadeId) :
                new ObjectParameter("CidadeId", typeof(int));
    
            var municipioIdParameter = municipioId.HasValue ?
                new ObjectParameter("MunicipioId", municipioId) :
                new ObjectParameter("MunicipioId", typeof(int));
    
            var isentoParameter = isento.HasValue ?
                new ObjectParameter("Isento", isento) :
                new ObjectParameter("Isento", typeof(bool));
    
            var userInsercaoIdParameter = userInsercaoId.HasValue ?
                new ObjectParameter("UserInsercaoId", userInsercaoId) :
                new ObjectParameter("UserInsercaoId", typeof(int));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PES_ENT_PESSOAS_FAM_Result>("SP_PES_ENT_PESSOAS_FAM", idParameter, pesIdParameter, grupoIdParameter, profissaoIdParameter, nomeParameter, telefoneParameter, telefoneAlternativoParameter, faxParameter, emailParameter, uRlParameter, numeroParameter, ruaParameter, moradaParameter, paisIdParameter, cidadeIdParameter, municipioIdParameter, isentoParameter, userInsercaoIdParameter, actionParameter);
        }
    }
}
